apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: mysql
      # pod definition file
  template:
    metadata:
      labels: 
        project: roboshop
        environment: dev
        component: mysql
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    environment: dev
    component: mysql
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port